appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ItxvqcXkXbqrcEjcPfhtBE+yXrWNK+VtAM00gQ+dZ58ZoviMbR2UqlLkNK2pYf8ougdfXQT0CASd7V0T/a7B/7q9NNpiX0r5nqfqY/FhSJko4AbJdMg/Juf050xYB8ESzCcyCHP8aEvJeFLs6qHn8398Dy43wF2sKKdLH0ulo4qy335bUwL6R081Rf0E+iLD1BbNCNHihXJ6X+1LlJ1gzvEe4ebSnYskuN8aGEitx9YH5SnIC65nQ5HL6QxN6vqVH9eUcUo+DZfrp20t7V5CqtPL/TGkUxt0znPgLNDjdJjkcW4FnYKAZJTUYQMx+ozG0krujdJC6+ACjFBXCeMjosJwzMPlvGZBgUB6oXT2ONtM0F70yWRyHMjlBg3cgfY5AXVbneSqqoc9/OwAz6fA6QSFxuf8f6ygR3SR2r+tgWRRvWo8dTXj7O0ClXwwblWoZ0Fe1xq7kmRsApb6NEazX7arc1AwKxUWg4EblqLd87PnG7+SO+2uYAbAju7S4btkbqcVIWFGknuPCGT9TwQ+bDJb0ihq+AnwJwxC31BbPeqo6IDbVLGZHh/BKjVTmt136KKOaYnIMcH8bmUXHzUBcHMVKAwxZvoVfw/R8uVbplVg6hWWo1wrCeMn/flhIMdMwp1IVrbJ+qCTWRcOs39BLu83XHwbtW+4KfgdT0TBp7E=}
